language: python
python:
  - "2.7"
env:
  - DB=sqlite
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar &"
  - "export GOCEPT_SELENIUM_BROWSER='*firefox'"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt --use-mirrors
# command to run tests, e.g. python setup.py test
before_script:
  - "pep8 --exclude=migrations ."
  - "pyflakes ."
  - "python manage.py syncdb --noinput"
script:
  - python manage.py test lists